//
// Callback Agent (to deliver message to a consumer)
//

module CMQ {

	typedef any Message_t;

	interface Channel;
	interface CallbackAgent {
		oneway void callback(in Channel ch, in Message_t body);
	};

};
